import datetime

from werkzeug.security import generate_password_hash

default_data = {
    'GroupSi': [
        {'name': 'Радиотехнические и радиоэлектронные измерения'},
        {'name': 'Измерения электрических и магнитных величин'},
        {'name': 'Измерения параметров потока, расхода, уровня, объма веществ'},
        {'name': 'Теплофизические и температурные измерения'},
        {'name': 'Измерения давления, вакуумные измерения'},
        {'name': 'Измерения времени и частоты'},
        {'name': 'Измерения механических величин'},
        {'name': 'Измерения физико-химического состава и свойств веществ'},
        {'name': 'Оптические и оптико-физические измерения'},
        {'name': 'Виброакустические измерения'},
        {'name': 'Измерения характеристик ионизирующих излучений и ядерных констант'},
        {'name': 'Измерения электрических и магнитных величин, радиотехнические и радиоэлектронныя измерения'},
        {'name': 'Геометрические измерения'},
    ],
    'NameSi': 'Наименование',
    'TypeSi': 'Тип',
    'ServiceType': [
        {'name': 'Аттестация'},
        {'name': 'Калибровка'},
        {'name': 'Поверка'},
    ],
    'ServiceInterval': [
        {'name': 12},
        {'name': 24},
        {'name': 30},
        {'name': 36},
        {'name': 48},
        {'name': 60},
        {'name': 120},
    ],
    'DescriptionMethod': [
        {'name': 'описание типа 1'},
        {'name': 'описание типа 2'},
        {'name': 'описание типа 3'},
    ],
    'Place': [
        {'name': 'АО "НИИП"'},
        {'name': 'Сторонняя организация'},
    ],
    'Room': [
        {'name': '082'},
        {'name': '283'},
        {'name': '286'},
        {'name': '287'},
    ],
    'Division': [
        {'name': '4'},
        {'name': '5'},
        {'name': '7'},
        {'name': '11'},
        {'name': '59'},
        {'name': '74'},
        {'name': '81'},
        {'name': '82'},
        {'name': '84'},
        {'name': '92'},
        {'name': '97'},
        {'name': '601'},
        {'name': '602'},
        {'name': '5(11)'},
        {'name': '5(601)'},
        {'name': '5(81)'},
        {'name': '5(82)'},
        {'name': 'ДДС'},
        {'name': 'РЭБ'},
        {'name': 'У200'},
    ],
    'Employee': [
        {
            'last_name': 'Гфамилия',
            'first_name': 'Аимя',
            'middle_name': 'Уотчество',
            'email': 'a@a.ru',
            'division_id': 1,
        },
        {
            'last_name': 'Уфамилия',
            'first_name': 'Димя',
            'middle_name': 'Ботчество',
            'email': 'b@a.ru',
            'division_id': 2,
        },
        {
            'last_name': 'Кфалилия',
            'first_name': 'Пимя',
            'middle_name': 'Мотчество',
            'email': 'c@a.ru',
            'division_id': 3,
        },
    ],
    'Si': [
        {
            'group_si_id': 1,
            'name_si_id': 1,
            'type_si_id': 1,
            'number': 'номер 1',
            'service_type_id': 1,
            'service_interval_id': 1,
            'etalon': 0,
            'category_etalon': '2',
            'year_production': 1999,
            'nomenclature': '1111',
            'room_use_etalon': 'room_use_etalon',
            'description_method_id': 1,
            'place_id': 1,
            'control_vp': True,
            'room_delivery_id': 1,
            'employee_id': 1,
            'date_last_service': datetime.datetime(2000, 0o1, 0o2),
            'date_next_service': datetime.datetime(2001, 0o1, 0o2),
            'certificate': 'certificate 1',
            'is_service': False,
        },
        {
            'group_si_id': 1,
            'name_si_id': 1,
            'type_si_id': 1,
            'number': 'номер 2',
            'service_type_id': 1,
            'service_interval_id': 1,
            'etalon': False,
            'category_etalon': '2',
            'year_production': 2010,
            'nomenclature': '2222',
            'room_use_etalon': 'room_use_etalon',
            'description_method_id': 1,
            'place_id': 1,
            'control_vp': True,
            'room_delivery_id': 1,
            'employee_id': 2,
            'date_last_service': datetime.datetime(2010, 0o1, 0o2),
            'date_next_service': datetime.datetime(2011, 0o1, 0o2),
            'certificate': 'certificate 2',
            'is_service': True,
        },
        {
            'group_si_id': 1,
            'name_si_id': 1,
            'type_si_id': 1,
            'number': 'номер 3',
            'service_type_id': 1,
            'service_interval_id': 1,
            'etalon': 0,
            'category_etalon': '2',
            'year_production': 2020,
            'nomenclature': '3333',
            'room_use_etalon': 'room_use_etalon',
            'description_method_id': 1,
            'place_id': 1,
            'control_vp': True,
            'room_delivery_id': 1,
            'employee_id': 3,
            'date_last_service': datetime.datetime(2020, 0o1, 0o2),
            'date_next_service': datetime.datetime(2021, 0o1, 0o2),
            'certificate': 'certificate 3',
            'is_service': True,
        },
    ],
    'UserProfile': [
        {
            'username': 'admin',
            'password': generate_password_hash('123'),
            'last_name': 'фамилия админа',
            'first_name': 'Имя админа',
            'middle_name': 'Отчество админа',
            'email': 'admin@si.ru',
            'is_active': True,
        },
        {
            'username': 'user',
            'password': generate_password_hash('123'),
            'last_name': 'фамилия юзера',
            'first_name': 'Имя юзера',
            'middle_name': 'Отчество юзера',
            'email': 'user@si.ru',
            'is_active': True,
        },
    ],
}
